# Generated by Django 3.1.5 on 2021-03-20 14:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210320_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ph_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=10, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
