# Generated by Django 3.1.5 on 2021-03-20 14:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210320_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, region=None),
        ),
    ]
