# Generated by Django 3.1.5 on 2021-03-20 15:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, region=None),
        ),
    ]
