# Generated by Django 3.1.5 on 2021-03-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210320_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='ph_number',
        ),
    ]
