# Generated by Django 3.1.5 on 2021-04-09 03:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210320_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, null=True, region=None),
        ),
    ]
