# Generated by Django 3.1.5 on 2021-04-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210409_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='Self_Notes',
        ),
    ]
